/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.HangHoaBLL;
import BLL.LoaiHangBLL;
import DTO.HangHoaDTO;
import DTO.LoaiHangDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.SystemColor;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author ACER
 */
public class Chart_SoLuongTheoLoai extends javax.swing.JFrame {

    /**
     * Creates new form chart
     */
    public Chart_SoLuongTheoLoai() {
        initComponents();
        addControl();
    }
    private void addControl(){
        DefaultPieDataset dataset = new DefaultPieDataset();
    // Create a set of charts
         JFreeChart jfreeChart;
    // Create a set of panels that can show charts
        ChartPanel chartPanel;
        //Set gia tr cho PieChart
        ArrayList<HangHoaDTO> arr = new ArrayList<HangHoaDTO>();
	HangHoaBLL hangBLL = new HangHoaBLL();
	arr = hangBLL.TK_SLuongTheoLoai();
        HangHoaDTO hangDTO = new HangHoaDTO();
	for (int i = 0; i < arr.size(); i++) {
            hangDTO = arr.get(i);
            String typeId=hangDTO.getMA_LOAI();
            LoaiHangDTO loaiDTO=new LoaiHangDTO();
            loaiDTO.setMA_LOAI(typeId);
            LoaiHangBLL loaiBLL=new LoaiHangBLL();
            String typeName=loaiBLL.getTenLoai(loaiDTO);
            int soLuong=hangDTO.getSO_LUONG();
            dataset.setValue(typeName, soLuong);
	}
        

        jfreeChart = ChartFactory.createPieChart3D("THỐNG KÊ SỐ LƯỢNG HÀNG THEO LOẠI HÀNG", dataset, true, true, false);
        PiePlot3D plot = (PiePlot3D) jfreeChart.getPlot();        
        plot.setBackgroundPaint(new Color(255, 255, 255)); //Set background cho PieChart

        // add chartPanel PieChart vao panel
        chartPanel = new ChartPanel(jfreeChart);
        chartPanel.setBounds(80, 70, 442, 232); //set size PieChart
        panel.add(chartPanel);
        //panel.setSize(500,200);
        panel.setBackground(Color.WHITE);
        chartPanel.setMouseWheelEnabled(true);
        chartPanel.setZoomAroundAnchor(true);
        chartPanel.setBackground(SystemColor.menu);
        chartPanel.setSize(1100,490);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
