/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.NhanVienBLL;
import BLL.QuyenBLL;
import BLL.TaiKhoanBLL;
import DTO.NhanVienDTO;
import DTO.QuyenDTO;
import DTO.TaiKhoanDTO;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Frm_QLTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form Frm_QLTaiKhoan
     */
    public String username;
    public Frm_QLTaiKhoan() {
        initComponents();
        addControl();
        addComboBoxMaNV();
        addComboBoxMaQuyen();
        loadAll();
    }
    
    private void addControl(){
        Font ft=new Font("Times New Roman",Font.BOLD,24);
        tk1.setFont(ft);
        paneltk.setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        this.setTitle("Quản Lý Tài Khoản");
        btn1.setBackground(Color.PINK);
        btn2.setBackground(Color.PINK);
        btn3.setBackground(Color.PINK);
        btn4.setBackground(Color.PINK);        
        btn9.setBackground(Color.PINK);
        tk1.requestFocus();
        
        tf1.setText("Nhập username");
        tf2.setText("Nhập password");
        tf6.setText("Nhập dữ liệu cần tìm");
        
        tf1.setForeground(Color.DARK_GRAY);
        tf2.setForeground(Color.DARK_GRAY);
        tf6.setForeground(Color.DARK_GRAY);
    }
    
    private void addComboBoxMaNV(){
        ArrayList<NhanVienDTO> arr = new ArrayList<NhanVienDTO>();
	 NhanVienBLL nvBLL = new NhanVienBLL();
	 arr = nvBLL.getAllNvien();	 
	 NhanVienDTO nvDTO = new NhanVienDTO();
	 for (int i = 0; i < arr.size(); i++) {
		 nvDTO = arr.get(i);
		 cbManv.addItem(nvDTO.getMA_NV()+"-"+nvDTO.getTEN_NV());		 
	 }
    }
    
    private void addComboBoxMaQuyen(){
        ArrayList<QuyenDTO> arr = new ArrayList<QuyenDTO>();
	 QuyenBLL qBLL = new QuyenBLL();
	 arr = qBLL.getAllQuyen();	 
	 QuyenDTO qDTO = new QuyenDTO();
	 for (int i = 0; i < arr.size(); i++) {
		 qDTO = arr.get(i);
		 cbMaq.addItem(qDTO.getMA_QUYEN()+"-"+qDTO.getTEN_QUYEN());		 
	 }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        paneltk = new javax.swing.JPanel();
        tk1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        btn9 = new javax.swing.JButton();
        tf6 = new javax.swing.JTextField();
        cbManv = new javax.swing.JComboBox<>();
        cbMaq = new javax.swing.JComboBox<>();
        rd1 = new javax.swing.JRadioButton();
        rd2 = new javax.swing.JRadioButton();
        cb3 = new javax.swing.JComboBox<>();

        tk1.setText("QUẢN LÍ TÀI KHOẢN");

        jLabel1.setText("     Username:");

        jLabel2.setText("     Password:");

        jLabel3.setText("     Mã nhân viên:");

        jLabel4.setText("     Mã quyền:");

        jLabel5.setText("     Khóa:");

        btn2.setText("THÊM");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("SỬA");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("XÓA");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn1.setText("TÌM KIẾM");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf1FocusLost(evt);
            }
        });
        tf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf1MouseClicked(evt);
            }
        });
        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf1KeyPressed(evt);
            }
        });

        tf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf2FocusLost(evt);
            }
        });
        tf2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf2MouseClicked(evt);
            }
        });

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "USERNAME", "PASSWORD", "Mã Nhân viên", "Mã quyền", "Khóa"
            }
        ));
        tb1.setRowHeight(20);
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        btn9.setText("XEM TẤT CẢ");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        tf6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf6FocusLost(evt);
            }
        });
        tf6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf6MouseClicked(evt);
            }
        });
        tf6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf6KeyPressed(evt);
            }
        });

        cbManv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Chọn Mã nhân viên]" }));

        cbMaq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Chọn Mã quyền]" }));

        buttonGroup1.add(rd1);
        rd1.setText("Có");

        buttonGroup1.add(rd2);
        rd2.setSelected(true);
        rd2.setText("Không");

        cb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Username", "Mã Nhân viên" }));

        javax.swing.GroupLayout paneltkLayout = new javax.swing.GroupLayout(paneltk);
        paneltk.setLayout(paneltkLayout);
        paneltkLayout.setHorizontalGroup(
            paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltkLayout.createSequentialGroup()
                .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneltkLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneltkLayout.createSequentialGroup()
                                .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf6)
                                .addGap(18, 18, 18)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneltkLayout.createSequentialGroup()
                                .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneltkLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(rd1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rd2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltkLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbMaq, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(paneltkLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbManv, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltkLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltkLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneltkLayout.createSequentialGroup()
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneltkLayout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(tk1)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        paneltkLayout.setVerticalGroup(
            paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltkLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(tk1)
                .addGap(80, 80, 80)
                .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneltkLayout.createSequentialGroup()
                        .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbManv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMaq, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rd2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rd1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneltk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltk, javax.swing.GroupLayout.PREFERRED_SIZE, 595, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        TaiKhoanDTO tkDTO=new TaiKhoanDTO();
        tkDTO.setUSERNAME(tf1.getText());
        if(tf1.getText().equals("Nhập username")) 
            JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin username.","Thông báo",0);
        else{
            TaiKhoanBLL tkBLL=new TaiKhoanBLL();
            int choice = JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn muốn xóa dữ liệu?", "Xác nhận",JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION){
                if (tkBLL.deletetAccount(tkDTO)!=0) {
                    loadAll();                
                    JOptionPane.showMessageDialog(null, "Xoá thành công!","Thông báo",1);
                     tf1.setText("");
                     tf2.setText("");
                     cbManv.setSelectedIndex(0);
                     cbMaq.setSelectedIndex(0);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Username này không tồn tại","Thông báo",0);
                }
            }
            
        } 
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        TaiKhoanDTO tkDTO=new TaiKhoanDTO();
        if(tf1.getText().equals("Nhập username")||tf2.getText().equals("Nhập password")){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin username và password.","Thông báo",0);
        }
        else{
            //String username=tf1.getText();
            tkDTO.setUSERNAME(tf1.getText());
            tkDTO.setPASSWORD(tf2.getText());
            String value1=(String) cbManv.getSelectedItem();
            String maNv="";
            if(cbManv.getSelectedIndex()==0) JOptionPane.showMessageDialog(null, "Vui lòng chọn Mã nhân viên","Thông báo",0);
            else{
                maNv=value1.substring(0, 3);
                tkDTO.setMA_NV(maNv);
                String value2=(String) cbMaq.getSelectedItem();
                String maQ="";
                if(cbMaq.getSelectedIndex()==0) JOptionPane.showMessageDialog(null, "Vui lòng chọn Mã quyền","Thông báo",0);
                else{
                    maQ=value2.substring(0, 2);
                    tkDTO.setMA_QUYEN(maQ);
                    if(rd1.isSelected()) tkDTO.setKHOA(1);
                    else   tkDTO.setKHOA(0);
                        
                    
                    TaiKhoanBLL tkBLL=new TaiKhoanBLL();
                    if (tkBLL.updateAccount(tkDTO,username)!=0) {
                        loadAll();
                        JOptionPane.showMessageDialog(null, "Sửa tài khoản thành công!","Thông báo",1);
                        tf1.setText("");
                        tf2.setText("");
                        cbManv.setSelectedIndex(0);
                        cbMaq.setSelectedIndex(0);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Sửa tài khoản thất bại!","Thông báo",0);
                    }
                }
                            

            }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        loadAll();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        TaiKhoanDTO tkDTO=new TaiKhoanDTO();
        if(tf1.getText().equals("Nhập username")||tf2.getText().equals("Nhập password")){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin username và password.","Thông báo",0);
        }
        else{
            tkDTO.setUSERNAME(tf1.getText());
            tkDTO.setPASSWORD(tf2.getText());
            String value1=(String) cbManv.getSelectedItem();
            String maNv="";
            if(cbManv.getSelectedIndex()==0) JOptionPane.showMessageDialog(null, "Vui lòng chọn Mã nhân viên","Thông báo",0);
            else{
                maNv=value1.substring(0, 3);
                tkDTO.setMA_NV(maNv);
                String value2=(String) cbMaq.getSelectedItem();
                String maQ="";
                if(cbMaq.getSelectedIndex()==0) JOptionPane.showMessageDialog(null, "Vui lòng chọn Mã quyền","Thông báo",0);
                else{
                    maQ=value2.substring(0, 2);
                    tkDTO.setMA_QUYEN(maQ);
                    if(rd1.isSelected()) tkDTO.setKHOA(1);
                    else   tkDTO.setKHOA(0);
                    TaiKhoanBLL tkBLL=new TaiKhoanBLL();
                    if (tkBLL.insertAccount(tkDTO)!=0) {
                        loadAll();
                        JOptionPane.showMessageDialog(null, "Thêm tài khoản thành công!","Thông báo",1);
                        tf1.setText("");
                        tf2.setText("");
                        cbManv.setSelectedIndex(0);
                        cbMaq.setSelectedIndex(0);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Thêm tài khoản thất bại!","Thông báo",0);
                    }
                }
                            

            }
        }
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        int selectedIndex=tb1.getSelectedRow();
                
        if(tb1.getModel().getValueAt(selectedIndex,0)!=null&&tb1.getModel().getValueAt(selectedIndex,1)!=null&&tb1.getModel().getValueAt(selectedIndex,2)!=null&&tb1.getModel().getValueAt(selectedIndex,3)!=null&&tb1.getModel().getValueAt(selectedIndex,4)!=null){        
        tf1.setText(tb1.getModel().getValueAt(selectedIndex,1).toString());
        tf1.setForeground(Color.BLACK);
        username=tb1.getModel().getValueAt(selectedIndex,1).toString();
        tf2.setText(tb1.getModel().getValueAt(selectedIndex,2).toString());
        tf2.setForeground(Color.BLACK);
        
        NhanVienDTO nvDTO=new NhanVienDTO();
        NhanVienBLL nvBLL=new NhanVienBLL();
        nvDTO.setMA_NV(tb1.getModel().getValueAt(selectedIndex,3).toString());
        String ten=nvDTO.getMA_NV()+"-"+nvBLL.getTenNV(nvDTO);
        cbManv.setSelectedItem(ten);
        
        QuyenDTO qDTO=new QuyenDTO();
        QuyenBLL qBLL=new QuyenBLL();
        qDTO.setMA_QUYEN(tb1.getModel().getValueAt(selectedIndex,4).toString());
        String quyen=qDTO.getMA_QUYEN()+"-"+qBLL.getTenQ(qDTO);
        cbMaq.setSelectedItem(quyen);
        if(Integer.parseInt(tb1.getModel().getValueAt(selectedIndex,5).toString())==1) rd1.setSelected(true);
        else rd2.setSelected(true);
        }
    }//GEN-LAST:event_tb1MouseClicked

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        TaiKhoanDTO tkDTO=new TaiKhoanDTO();
        if(cb3.getSelectedIndex()==0){
             tkDTO.setUSERNAME(tf6.getText());
            if(tf6.getText().equals("Nhập dữ liệu cần tìm")){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin Username cần tìm!","Thông báo",0);
            }
            else      
                getAccountUS(tkDTO);
        }
        else{
             tkDTO.setMA_NV(tf6.getText());
            if(tf6.getText().equals("Nhập dữ liệu cần tìm")){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin Mã nhân viên cần tìm!","Thông báo",0);
            }
            else      
                getAccountManv(tkDTO);
        }
       
    }//GEN-LAST:event_btn1ActionPerformed

    private void tf6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf6KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){            
            btn1.doClick();
        }
    }//GEN-LAST:event_tf6KeyPressed

    private void tf1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){            
            tf2.requestFocus();
        }
    }//GEN-LAST:event_tf1KeyPressed

    private void tf1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf1MouseClicked
        // TODO add your handling code here:
        if(tf1.getText().equals("Nhập username")){
            tf1.setText("");
            tf1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf1MouseClicked

    private void tf2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf2MouseClicked
        // TODO add your handling code here:
        if(tf2.getText().equals("Nhập password")){
            tf2.setText("");
            tf2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf2MouseClicked

    private void tf6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf6MouseClicked
        // TODO add your handling code here:
        if(tf6.getText().equals("Nhập dữ liệu cần tìm")){
            tf6.setText("");
            tf6.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf6MouseClicked

    private void tf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusLost
        // TODO add your handling code here:
        if(tf1.getText().equals("")){
            tf1.setText("Nhập username");
            tf1.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_tf1FocusLost

    private void tf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusLost
        // TODO add your handling code here:
        if(tf2.getText().equals("")){
            tf2.setText("Nhập password");
            tf2.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_tf2FocusLost

    private void tf6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf6FocusLost
        // TODO add your handling code here:
        if(tf6.getText().equals("")){
            tf6.setText("Nhập dữ liệu cần tìm");
            tf6.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_tf6FocusLost

    private void tf2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusGained
        // TODO add your handling code here:
        if(tf2.getText().equals("Nhập password")){
            tf2.setText("");
            tf2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf2FocusGained

    public void loadAll() {
	String[] header = { "STT","USERNAME","PASSWORD", "Mã nhân viên", "Mã quyền", "Khóa"};
	DefaultTableModel dtm = new DefaultTableModel(header, 0);	 
	ArrayList<TaiKhoanDTO> arr = new ArrayList<TaiKhoanDTO>();
	 TaiKhoanBLL tkBLL = new TaiKhoanBLL();
	 arr = tkBLL.getAllAccount();
	 TaiKhoanDTO tkDTO = new TaiKhoanDTO();
	 for (int i = 0; i < arr.size(); i++) {
		 tkDTO = arr.get(i);		 
		 String username = tkDTO.getUSERNAME();
		 String password = tkDTO.getPASSWORD();	
                 String ma_nv = tkDTO.getMA_NV();
		 String ma_quyen = tkDTO.getMA_QUYEN();
                 int lock = tkDTO.getKHOA();
                 
		  Object[] row = {i+1, username, password,ma_nv,ma_quyen,lock};
		 dtm.addRow(row);
	 }
	 tb1.setModel(dtm);
    }
    
    public void getAccountUS(TaiKhoanDTO tkDTO) {
	String[] header = { "STT","USERNAME","PASSWORD", "Mã nhân viên", "Mã quyền", "Khóa"};
	DefaultTableModel dtm = new DefaultTableModel(header, 0);	 
	ArrayList<TaiKhoanDTO> arr = new ArrayList<TaiKhoanDTO>();
	 TaiKhoanBLL tkBLL = new TaiKhoanBLL();
	 arr = tkBLL.searchAccountUS(tkDTO);
	 for (int i = 0; i < arr.size(); i++) {
		 tkDTO = arr.get(i);		 
		 String username = tkDTO.getUSERNAME();
		 String password = tkDTO.getPASSWORD();	
                 String ma_nv = tkDTO.getMA_NV();
		 String ma_quyen = tkDTO.getMA_QUYEN();
                 int lock = tkDTO.getKHOA();
                 
		  Object[] row = { i+1,username, password,ma_nv,ma_quyen,lock};
		 dtm.addRow(row);
	 }
         if(arr.size()==0) JOptionPane.showMessageDialog(null, "Tài khoản này không tồn tại.","Thông báo",0);
	 tb1.setModel(dtm);
    }
    public void getAccountManv(TaiKhoanDTO tkDTO) {
	String[] header = { "STT","USERNAME","PASSWORD", "Mã nhân viên", "Mã quyền", "Khóa"};
	DefaultTableModel dtm = new DefaultTableModel(header, 0);	 
	ArrayList<TaiKhoanDTO> arr = new ArrayList<TaiKhoanDTO>();
	 TaiKhoanBLL tkBLL = new TaiKhoanBLL();
	 arr = tkBLL.searchAccountManv(tkDTO);
	 for (int i = 0; i < arr.size(); i++) {
		 tkDTO = arr.get(i);		 
		 String username = tkDTO.getUSERNAME();
		 String password = tkDTO.getPASSWORD();	
                 String ma_nv = tkDTO.getMA_NV();
		 String ma_quyen = tkDTO.getMA_QUYEN();
                 int lock = tkDTO.getKHOA();
                 
		  Object[] row = { i+1,username, password,ma_nv,ma_quyen,lock};
		 dtm.addRow(row);
	 }
         if(arr.size()==0) JOptionPane.showMessageDialog(null, "Tài khoản này không tồn tại.","Thông báo",0);
	 tb1.setModel(dtm);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JComboBox<String> cbManv;
    private javax.swing.JComboBox<String> cbMaq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paneltk;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd2;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf6;
    private javax.swing.JLabel tk1;
    // End of variables declaration//GEN-END:variables
}
