
package GUI;

import BLL.ChiTietPX_BLL;
import BLL.HangHoaBLL;
import BLL.KhachHangBLL;
import BLL.PXuatBLL;
import DTO.ChiTietPX_DTO;
import DTO.HangHoaDTO;
import DTO.KhachHangDTO;
import DTO.NhanVienDTO;
import DTO.PXuatDTO;
import java.awt.*;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class Frm_LapPX extends javax.swing.JFrame {

    String[] header = { "STT","MÃ HÀNG","TÊN HÀNG","ĐƠN GIÁ","SỐ LƯỢNG","THÀNH TIỀN"};
    DefaultTableModel dtm = new DefaultTableModel(header, 0); 
    int stt=0;
    int tongTien=0;
    public Frm_LapPX() {
        initComponents();
        addControl();
        addComboBoxKH();
        setMaPN();
        addComboBoxMaPX();
         tfDate.setText(String.valueOf(java.time.LocalDate.now()));
    }
    
    private void addControl(){
        Font ft=new Font("Times New Roman",Font.BOLD,24);
        lbl1.setFont(ft);
        panel.setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        this.setTitle("Lập phiếu xuất");
        btnadd.setBackground(Color.PINK);
        btn1.setBackground(Color.PINK);
        btnsearch.setBackground(Color.PINK);  
        btnReport.setBackground(Color.PINK);
        tf1.setText("Nhập Mã hàng");
        tf2.setText("Nhập số lượng");
        tf1.setForeground(Color.DARK_GRAY);
        tf2.setForeground(Color.DARK_GRAY);
        
    }

    public void addComboBoxKH(){
        ArrayList<KhachHangDTO> arr = new ArrayList<KhachHangDTO>();
	 KhachHangBLL khBLL = new KhachHangBLL();
	 arr = khBLL.getAllK_Hang();	 
	 KhachHangDTO khDTO = new KhachHangDTO();
	 for (int i = 0; i < arr.size(); i++) {
		 khDTO = arr.get(i);
		 cb1.addItem(khDTO.getMA_KH()+"-"+khDTO.getTEN_KH());		 
	 }
    }
    private void setMaPN(){
        PXuatBLL pxBLL=new PXuatBLL();
        lblMAPX.setText(pxBLL.getMaPX());
    }
    private void addComboBoxMaPX(){
        ArrayList<PXuatDTO> arr = new ArrayList<PXuatDTO>();
	 PXuatBLL pxBLL = new PXuatBLL();
	 arr = pxBLL.getAllPXuat();	 
	 PXuatDTO pxDTO = new PXuatDTO();
	 for (int i = 0; i < arr.size(); i++) {
		 pxDTO = arr.get(i);
		 cbMaPX.addItem(pxDTO.getMA_PX());		 
	 }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lblmaphieu = new javax.swing.JLabel();
        lblmakh = new javax.swing.JLabel();
        lblngayxuat = new javax.swing.JLabel();
        lblmanv = new javax.swing.JLabel();
        lbltongtien = new javax.swing.JLabel();
        tfDate = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpxuat = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTien = new javax.swing.JLabel();
        lblMAPX = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        lblMANV = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbMaPX = new javax.swing.JComboBox<>();
        btnadd3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl1.setText("LẬP PHIẾU XUẤT");

        lblmaphieu.setText("MÃ PHIẾU:");

        lblmakh.setText("   MÃ NHÂN VIÊN:");

        lblngayxuat.setText("NGÀY XUẤT HÀNG:");

        lblmanv.setText("   KHÁCH HÀNG:");

        lbltongtien.setBackground(new java.awt.Color(0, 153, 255));
        lbltongtien.setText("      TỔNG TIỀN:");

        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf1FocusLost(evt);
            }
        });
        tf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf1MouseClicked(evt);
            }
        });

        tf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf2FocusLost(evt);
            }
        });
        tf2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf2MouseClicked(evt);
            }
        });

        tbpxuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MÃ HÀNG", "TÊN HÀNG", "ĐƠN GIÁ", "SỐ LƯỢNG", "THÀNH TIỀN"
            }
        ));
        tbpxuat.setRowHeight(20);
        jScrollPane1.setViewportView(tbpxuat);
        if (tbpxuat.getColumnModel().getColumnCount() > 0) {
            tbpxuat.getColumnModel().getColumn(1).setResizable(false);
            tbpxuat.getColumnModel().getColumn(5).setResizable(false);
        }

        btnadd.setText("TẠO PHIẾU");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsearch.setText("TÌM");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel1.setText("MÃ PHIẾU:");

        lblTien.setText("0");

        lblMAPX.setText("    .....");

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Chọn Khách hàng]" }));

        lblMANV.setText(".....");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("     MÃ HÀNG:");

        jLabel3.setText("     SỐ LƯỢNG:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("THÊM HÀNG");

        cbMaPX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Chọn Mã phiếu]" }));
        cbMaPX.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMaPXItemStateChanged(evt);
            }
        });

        btnadd3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnadd3.setText("...");
        btnadd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd3ActionPerformed(evt);
            }
        });

        btn1.setText("THÊM");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnReport.setText("IN PHIẾU");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblngayxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(lblMAPX, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(lbltongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTien, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnadd3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbMaPX, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(123, 123, 123)))
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addComponent(lblmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblMANV, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(panelLayout.createSequentialGroup()
                                                        .addComponent(lblmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMAPX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMANV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblngayxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbMaPX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnadd3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Frm_ThemKH addKH=new Frm_ThemKH();
        addKH.setVisible(true);
        addKH.PX=this;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnadd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd3ActionPerformed
        // TODO add your handling code here:
        Frm_ThemHang addItem=new Frm_ThemHang();
        addItem.setVisible(true);
        addItem.LapPX=this;
        addItem.btn1.setVisible(false);
        addItem.btn2.setVisible(false);
        addItem.btn4.setVisible(false);
    }//GEN-LAST:event_btnadd3ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        ChiTietPX_DTO ctpxDTO=new ChiTietPX_DTO();        
        if(tf1.getText().equals("Nhập Mã hàng")||tf2.getText().equals("Nhập số lượng")) 
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã hàng và số lượng!","Thông báo",0);
        else{
            ctpxDTO.setMA_PX(lblMAPX.getText());
            HangHoaDTO hangDTO=new HangHoaDTO();
            hangDTO.setMA_HANG(tf1.getText());
            ArrayList<HangHoaDTO> arr = new ArrayList<HangHoaDTO>();
            HangHoaBLL hangBLL = new HangHoaBLL();
            arr = hangBLL.searchHangMa(hangDTO);
            if(arr.size()==0) JOptionPane.showMessageDialog(null, "Mã sản phẩm này không tồn tại!","Thông báo",0);
            else{
                ctpxDTO.setMA_HANG(tf1.getText());
                String pattern="\\d{1,}";
                if(tf2.getText().matches(pattern )==false) JOptionPane.showMessageDialog(null, "Số lượng phải là số nguyên dương!","Thông báo",0);                
                else{
                    int so_luong=Integer.parseInt(tf2.getText());
                    ctpxDTO.setSO_LUONG(Integer.parseInt(tf2.getText()));
                    ChiTietPX_BLL ctpxBLL=new ChiTietPX_BLL();                
                    tongTien+=getCTPN2(dtm,stt);
                    stt++;
                    lblTien.setText(String.valueOf(tongTien));
                    tf1.setText("");
                }          
            }
            
            tf2.setText("");
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        KhachHangDTO khDTO=new KhachHangDTO();
        PXuatDTO pxDTO=new PXuatDTO();
        //lấy giá trị mã khách hàng từ combo box 1
        String value1=(String) cb1.getSelectedItem();
        String maKH="";
        if(cb1.getSelectedIndex()==0) JOptionPane.showMessageDialog(null, "Vui lòng chọn Khách hàng","Thông báo",0);
        else{
            for(int i=0;i<value1.length();i++){
                if(value1.charAt(i)!='-') maKH+=value1.charAt(i);
                else break;
            }
            pxDTO.setMA_KH(maKH);
            pxDTO.setNGAY_LAP(Date.valueOf(tfDate.getText()));
            pxDTO.setMA_NV(lblMANV.getText());           
             //set mã phiếu cho chi tiết phiếu xuất và phiếu xuất
            PXuatBLL pxBLL=new PXuatBLL();
            ChiTietPX_DTO ctpxDTO=new ChiTietPX_DTO();
            ChiTietPX_BLL ctpxBLL=new ChiTietPX_BLL();
            ctpxDTO.setMA_PX(lblMAPX.getText());
            pxDTO.setMA_PX(lblMAPX.getText());
            //chép dữ liệu từ table vào csdl (insert ctpx)
            if(tbpxuat.getModel().getValueAt(0,0)!=null&&tbpxuat.getModel().getValueAt(0,1)!=null){
                for(int i=0;i<tbpxuat.getModel().getRowCount();i++){
                    ctpxDTO.setMA_HANG(tbpxuat.getModel().getValueAt(i,1).toString());
                    ctpxDTO.setSO_LUONG(Integer.parseInt(tbpxuat.getModel().getValueAt(i,4).toString()));  
                    if(ctpxBLL.insertCtietPX(ctpxDTO)==0) {
                        JOptionPane.showMessageDialog(null, "Tạo phiếu xuất thất bại!","Thông báo",0);
                        break;
                    }   
                }
                //insert phiếu xuất
                if (pxBLL.insertPXuat(pxDTO)!=0) {               
                    JOptionPane.showMessageDialog(null, "Tạo phiếu xuất thành công!","Thông báo",1);
                    lblTien.setText(String.valueOf(pxDTO.getTONG_TIEN()));
                    for(int i=0;i<tbpxuat.getModel().getRowCount();i++){
                        HangHoaDTO hangDTO=new HangHoaDTO();
                        hangDTO.setMA_HANG(tbpxuat.getModel().getValueAt(i,1).toString());
                        HangHoaBLL hangBLL=new HangHoaBLL();                        
                        int num=Integer.parseInt(tbpxuat.getModel().getValueAt(i,4).toString());                        
                        if(hangBLL.updateSL(hangDTO, -num)==0) 
                            JOptionPane.showMessageDialog(null, "Cập nhật số lượng hàng còn lại thất bại!","Thông báo",0);
                    }  
                    addComboBoxMaPX();
                }
                else    JOptionPane.showMessageDialog(null, "Tạo phiếu xuất thất bại!","Thông báo",0); 
            }    
            else JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng cần xuất!","Thông báo",0);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        PXuatDTO pxDTO=new PXuatDTO();
        ChiTietPX_DTO ctpxDTO=new ChiTietPX_DTO();
        pxDTO.setMA_PX(String.valueOf(cbMaPX.getSelectedItem()));
        ctpxDTO.setMA_PX(String.valueOf(cbMaPX.getSelectedItem()));
        if(cbMaPX.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn Mã phiếu cần tìm!","Thông báo",0);
        }
        else{
                     
            getPX(pxDTO);
            getCTPX(ctpxDTO);
            
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        PXuatDTO pxDTO=new PXuatDTO();
        pxDTO.setMA_PX(lblMAPX.getText());
        PXuatBLL pxBLL=new PXuatBLL();        
        if(pxBLL.searchPXuat(pxDTO).size()==0) JOptionPane.showMessageDialog(null,"Vui lòng thực hiện tạo phiếu trước khi in!","Thông báo",0);
        else{
            pxDTO.setMA_PX(lblMAPX.getText());            
            pxBLL.XuatPX(pxDTO);
        }
        
    }//GEN-LAST:event_btnReportActionPerformed

    private void cbMaPXItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMaPXItemStateChanged
        // TODO add your handling code here:
        btnsearch.doClick();
    }//GEN-LAST:event_cbMaPXItemStateChanged

    private void tf1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf1MouseClicked
        // TODO add your handling code here:
        if(tf1.getText().equals("Nhập Mã hàng")){
            tf1.setText("");
            tf1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf1MouseClicked

    private void tf2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf2MouseClicked
        // TODO add your handling code here:
        if(tf2.getText().equals("Nhập số lượng")){
            tf2.setText("");
            tf2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf2MouseClicked

    private void tf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusLost
        // TODO add your handling code here:
        if(tf1.getText().equals("")){
            tf1.setText("Nhập Mã hàng");
            tf1.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_tf1FocusLost

    private void tf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusLost
        // TODO add your handling code here:
        if(tf2.getText().equals("")){
            tf2.setText("Nhập số lượng");
            tf2.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_tf2FocusLost

    public void getPX(PXuatDTO pxDTO) {
	 	 
	 ArrayList<PXuatDTO> arr = new ArrayList<PXuatDTO>();
         /*NhanVienDTO nvDTO=new NhanVienDTO();
         NhanVienBLL nvBLL=new NhanVienBLL();*/
	 PXuatBLL pxBLL = new PXuatBLL();    
         KhachHangBLL khBLL=new KhachHangBLL();
         KhachHangDTO khDTO=new KhachHangDTO();
	 arr = pxBLL.searchPXuat(pxDTO);
	 for (int i = 0; i < arr.size(); i++) {
            pxDTO = arr.get(i);		 
            lblMAPX.setText(pxDTO.getMA_PX()); 
            khDTO.setMA_KH(pxDTO.getMA_KH());
            cb1.removeAllItems();
            cb1.addItem(pxDTO.getMA_KH()+"-"+khBLL.getTenKH(khDTO));   
            tfDate.setText(String.valueOf(pxDTO.getNGAY_LAP()));
            lblMANV.setText(pxDTO.getMA_NV());            
            lblTien.setText(String.valueOf(pxDTO.getTONG_TIEN()));
	}        
	 
    }
   //add hàng vào bảng với csdl
    public void getCTPX(ChiTietPX_DTO ctpxDTO) {
	String[] header = { "STT","MÃ HÀNG","TÊN HÀNG","ĐƠN GIÁ","SỐ LƯỢNG","THÀNH TIỀN"};
	DefaultTableModel dtm = new DefaultTableModel(header, 0);	 
	ArrayList<ChiTietPX_DTO> arr = new ArrayList<ChiTietPX_DTO>();
	 ChiTietPX_BLL ctpxBLL = new ChiTietPX_BLL();
	 arr = ctpxBLL.searchCtietPX(ctpxDTO);	
         int Total=0;
	 for (int i = 0; i < arr.size(); i++) {
		 ctpxDTO = arr.get(i);		 
		 String id = ctpxDTO.getMA_HANG();
                 HangHoaDTO hangDTO=new HangHoaDTO();
                 hangDTO.setMA_HANG(id);
                 HangHoaBLL hangBLL=new HangHoaBLL();
		 String name = hangBLL.getTenHang(hangDTO);
                 int price=hangBLL.getGia(hangDTO);
                 int num=ctpxDTO.getSO_LUONG();
                 int ttien=price*num;
                 Total+=ttien;
		  Object[] row = { i+1,id, name,price,num,ttien};
		 dtm.addRow(row);
	 }
	 tbpxuat.setModel(dtm);
         lblTien.setText(String.valueOf(Total));
    }
    //add vào bảng ko dùng csdl
    public int getCTPN2(DefaultTableModel dtm,int i) {
	//int tongTien=0;
	String id =tf1.getText();
        HangHoaDTO hangDTO=new HangHoaDTO();
        hangDTO.setMA_HANG(id);
        HangHoaBLL hangBLL=new HangHoaBLL();
	String name = hangBLL.getTenHang(hangDTO);
        int price=hangBLL.getGia(hangDTO);
        int num=Integer.parseInt(tf2.getText());
        int ttien=price*num;                 
        i++;
	Object[] row = { i,id, name,price,num,ttien};
	dtm.addRow(row);	 
	 tbpxuat.setModel(dtm);         
         return ttien;       
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd3;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cbMaPX;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    public javax.swing.JLabel lblMANV;
    private javax.swing.JLabel lblMAPX;
    private javax.swing.JLabel lblTien;
    private javax.swing.JLabel lblmakh;
    private javax.swing.JLabel lblmanv;
    private javax.swing.JLabel lblmaphieu;
    private javax.swing.JLabel lblngayxuat;
    private javax.swing.JLabel lbltongtien;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tbpxuat;
    public javax.swing.JTextField tf1;
    public javax.swing.JTextField tf2;
    private javax.swing.JTextField tfDate;
    // End of variables declaration//GEN-END:variables
}
